### ISSUE TITLE
Epwing v2 format broken by refactoring commit?

### ISSUE THREAD

**Issue by Enmankan** [eb4j/eb4j#67]
Hi, I noticed in the code that this refactoring:
https://github.com/eb4j/eb4j/commit/e78d9b5408f296825d9a3c29b2fc72586ebf22bc
might have introduced a bug.

In file `eb4j-core/src/main/java/io/github/eb4j/Book.java` in method `_loadCatalogEPWING` if `_version` of Epwing catalog is != 1 it will always throw, but before it threw only when some bytes that were read were not expected.

See here:
https://github.com/eb4j/eb4j/commit/e78d9b5408f296825d9a3c29b2fc72586ebf22bc#diff-5ba78a414312ebc84c522180cd441d58ccb3decb2592d3ed006a1e05eaab34bbR436

`int[] format = new int[3];` format was initialised to 0,
https://github.com/eb4j/eb4j/commit/e78d9b5408f296825d9a3c29b2fc72586ebf22bc#diff-5ba78a414312ebc84c522180cd441d58ccb3decb2592d3ed006a1e05eaab34bbL409

and then checked in a loop:
https://github.com/eb4j/eb4j/commit/e78d9b5408f296825d9a3c29b2fc72586ebf22bc#diff-5ba78a414312ebc84c522180cd441d58ccb3decb2592d3ed006a1e05eaab34bbL445

Initial value, when not changed, was interpreted as FORMAT_PLAIN and now the same case throws and makes Epwing format v2 not readable by this library.

Can you please have a look at this and let me know if I'm correct or am I missing something?

**Comment by miurahr** [comment]
Thank you for notice me the issue. I'd like to look into it.

**Comment by miurahr** [comment]
@Enmankan do you know a free v2 data to reproduce and test?

**Comment by miurahr** [comment]
@Enmankan Does #68 solve your case?

**Comment by miurahr** [comment]
Tested with EPWING v3 CDROM and confirmed working with patch.
